configure/mcg: fix Kit Marchand handling
Added a script "kitmarchand.sh" used to install or find the kitmarchand

configure:
    Use kitmarchand.sh to find the path where the kitmarchand is installed
    and save it into the variable KITMARCHAND.

gwk/setup.sh:
    Use kitmarchand.sh to find the where the kitmarchand is installed or
    setup it automatically.

Conflicts:

	configure
	mcg/modules/gwk/Makefile
	mcg/modules/gwk/setup.sh

Change-Id: Ia737ac5688f83a46c7e4e0c32acf541a4fe74c20

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -235,31 +235,7 @@ fi
 
 KITMARCHAND="$("$(dirname "$0")/mcg/modules/gwk/kitmarchand.sh" find)" \
 && setenv "KITMARCHAND" "$KITMARCHAND" \
-|| log "kit SIMPA SFR not found"
-
-# }}}
-# {{{ CCN SDK
-
-ccn0="/home/data/build/ccn"
-ccn1="/opt/ccn"
-ccn2="/srv/build/ccn"
-
-if file_exists "$ccn0"; then
-    setenv "ENABLE_CCN" "1"
-    setenv "WITH_CCN" "1"
-    setenv "CCN_PATH" "$ccn0"
-elif file_exists "$ccn1"; then
-    setenv "ENABLE_CCN" "1"
-    setenv "WITH_CCN" "1"
-    setenv "CCN_PATH" "$ccn1"
-elif file_exists "$ccn2"; then
-    setenv "ENABLE_CCN" "1"
-    setenv "WITH_CCN" "1"
-    setenv "CCN_PATH" "$ccn2"
-else
-    setenv "ENABLE_CCN" "0"
-    log "CCN SDK not found"
-fi
+|| echo 2>&1 "kit SIMPA SFR not found"
 
 # }}}
 # {{{ php
